name             'windows_firewall'
maintainer       'Chef Software, Inc.'
maintainer_email 'cookbooks@chef.io'
license          'Apache-2.0'
description      'Configures firewall rules on Windows'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '4.1.0'
supports         'windows'
source_url       'https://github.com/chef-cookbooks/windows_firewall'
issues_url       'https://github.com/chef-cookbooks/windows_firewall/issues'
chef_version     '>= 13.0'
