name             'windows_firewall'
maintainer       'Matt Clifton'
maintainer_email 'spartacus003@hotmail.com'
license          'All rights reserved'
description      'Configures firewall rules on Windows'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
#source_url       'https://github.com/lynx44/windows_firewall'
depends          'windows'
supports         'windows'
version          '0.1.0'
